version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: codeigniter4-app
    container_name: ci4-app
    restart: unless-stopped
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    networks:
      - ci4-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ci4-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ci4_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: db_password
      MYSQL_USER: ci4_user
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ci4-network

networks:
  ci4-network:
    driver: bridge

volumes:
  dbdata:
